controllers:
    resource: '../src/Controller/'
    type: attribute

persons_add:
    path: /persons/add
    controller: 'App\Controller\PersonsController::add'

persons_list:
    path: /persons/add
    controller: 'App\Controller\PersonsController::add'